# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/Nara-blog"

# ç½‘é¡µçš„æ ‡é¢˜
title: "ç§‘æŠ€é‡è§å¥¹"
username: Nara
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "Reshma Saujani: Teach girls bravery,not perfection"

aboutme: "åšå‹‡æ•¢çš„å¥³å­©ï¼Œè€Œéå®Œç¾ğŸ˜‰ğŸ•ğŸ§"

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
